### ISSUE TITLE
No Activity found to handle Intent android.intent.action.VIEW

### ISSUE THREAD

**Issue by justdave** [justdave/nwsweatheralertswidget#15]
Reported on the following OSes:
* Android 4.3	4	66.7%
* Android 4.2	1	16.7%
* Android 4.1	1	16.7%

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat= flg=0x10000000 }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1622)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1417)
at android.app.ContextImpl.startActivity(ContextImpl.java:949)
at android.app.ContextImpl.startActivity(ContextImpl.java:931)
at net.justdave.nwsweatheralertswidget.NWSAlertListViewAdapter$1.onClick(NWSAlertListViewAdapter.java:57)
at android.view.View.performClick(View.java:4207)
at android.view.View$PerformClick.run(View.java:17358)
at android.os.Handler.handleCallback(Handler.java:725)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5041)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by justdave** [comment]
This crash appears to be related to the widget opening the NWS website to view the alerts.  Reports of this crashed stopped when the version of the app which displays the alert text internally in the app was released.
