### ISSUE TITLE
Not able to update / retrieve data 

### ISSUE THREAD

**Issue by xenithorb** [justdave/nwsweatheralertswidget#27]
| | | 
---:|---
Phone:  | OnePlus One (bacon)
OS: | LineageOS 14.1 (Android 7.1.1) 
App Source:  | F-Droid
Version: | 1.1.3

Logcat: 

```
04-16 04:09:21.764  7755  8920 I ActivityManager: START u0 {dat= flg=0x10000000 cmp=net.justdave.nwsweatheralertswidget/.AlertDetailActivity} from uid 10353 on display 0
04-16 04:09:21.802  9952 10016 I AlertDetailActivity: Timer task fetching 
04-16 04:09:21.804  9952 10016 W System.err: java.net.MalformedURLException: no protocol: 
04-16 04:09:21.811  9952 10016 W System.err:    at java.net.URL.<init>(URL.java:589)
04-16 04:09:21.811  9952 10016 W System.err:    at java.net.URL.<init>(URL.java:486)
04-16 04:09:21.811  9952 10016 W System.err:    at java.net.URL.<init>(URL.java:435)
04-16 04:09:21.812  9952 10016 W System.err:    at net.justdave.nwsweatheralertswidget.AlertDetailActivity.sendHttpRequest(AlertDetailActivity.java:161)
04-16 04:09:21.812  9952 10016 W System.err:    at net.justdave.nwsweatheralertswidget.AlertDetailActivity.access$200(AlertDetailActivity.java:28)
04-16 04:09:21.812  9952 10016 W System.err:    at net.justdave.nwsweatheralertswidget.AlertDetailActivity$1.run(AlertDetailActivity.java:63)
04-16 04:09:21.812  9952 10016 W System.err:    at java.lang.Thread.run(Thread.java:761)
04-16 04:09:21.812  9952 10016 I AlertDetailActivity: URL retrieval complete.
04-16 04:09:21.818  9952 10016 I System.out: org.apache.harmony.xml.ExpatParser$ParseException: At line 1, column 0: no element found
04-16 04:09:21.872  7755  8701 I ActivityManager: Displayed net.justdave.nwsweatheralertswidget/.AlertDetailActivity: +97ms
```

**Comment by justdave** [comment]
OK, now that's kind of weird.  What did you have set for the state and county in your prefs?  The URL is taken from a static list on the config, and it picks from that list based on your preference.

**Comment by justdave** [comment]
Been several months with no response, and I can't debug this without more information.  It will notify me if you comment, so if you have more info to provide just comment and I can reopen the ticket.
